// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO user_credentials (user_id, type, identifier, secret_hash, verified_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, type, identifier, secret_hash, verified_at, created_at, updated_at, deleted_at
`

type CreateCredentialParams struct {
	UserID         uuid.UUID          `json:"user_id"`
	CredentialType string             `json:"credential_type"`
	Identifier     string             `json:"identifier"`
	SecretHash     *string            `json:"secret_hash"`
	VerifiedAt     pgtype.Timestamptz `json:"verified_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.UserID,
		arg.CredentialType,
		arg.Identifier,
		arg.SecretHash,
		arg.VerifiedAt,
	)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Identifier,
		&i.SecretHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO user_sessions (user_id, expires_at)
VALUES ($1, $2)
RETURNING id, user_id, expires_at, revoked_at, created_at, updated_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (display_name, locale)
VALUES ($1, $2)
RETURNING id, display_name, locale, status, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	DisplayName string `json:"display_name"`
	Locale      string `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.DisplayName, arg.Locale)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const findUserByCredential = `-- name: FindUserByCredential :one
SELECT users.id, users.display_name, users.locale, users.status, users.created_at, users.updated_at, users.deleted_at
FROM users
JOIN user_credentials ON user_credentials.user_id = users.id
WHERE user_credentials.type = $1
  AND user_credentials.identifier = $2
  AND user_credentials.deleted_at IS NULL
  AND users.deleted_at IS NULL
`

type FindUserByCredentialParams struct {
	CredentialType string `json:"credential_type"`
	Identifier     string `json:"identifier"`
}

func (q *Queries) FindUserByCredential(ctx context.Context, arg FindUserByCredentialParams) (User, error) {
	row := q.db.QueryRow(ctx, findUserByCredential, arg.CredentialType, arg.Identifier)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getActiveSession = `-- name: GetActiveSession :one
SELECT id, user_id, expires_at, revoked_at, created_at, updated_at
FROM user_sessions
WHERE id = $1
  AND revoked_at IS NULL
  AND expires_at > now()
`

func (q *Queries) GetActiveSession(ctx context.Context, id uuid.UUID) (UserSession, error) {
	row := q.db.QueryRow(ctx, getActiveSession, id)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCredentialByTypeIdentifier = `-- name: GetCredentialByTypeIdentifier :one
SELECT id, user_id, type, identifier, secret_hash, verified_at, created_at, updated_at, deleted_at
FROM user_credentials
WHERE type = $1
  AND identifier = $2
  AND deleted_at IS NULL
`

type GetCredentialByTypeIdentifierParams struct {
	CredentialType string `json:"credential_type"`
	Identifier     string `json:"identifier"`
}

func (q *Queries) GetCredentialByTypeIdentifier(ctx context.Context, arg GetCredentialByTypeIdentifierParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByTypeIdentifier, arg.CredentialType, arg.Identifier)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Identifier,
		&i.SecretHash,
		&i.VerifiedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, display_name, locale, status, created_at, updated_at, deleted_at
FROM users
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Locale,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE user_sessions
SET revoked_at = now(), updated_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
